### PR TITLE
Add argocd tests

### PR DESCRIPTION
**Pull request by chenz4027**
Add test cases to validate argocd app on the topology page. 

https://github.com/open-cluster-management/backlog/issues/10989
https://github.com/open-cluster-management/backlog/issues/10381

### CODE REVIEW

**Review by fxiang1 — APPROVED** [review]
Looks good! Thanks!

**Comment by birsanv** [comment]
@chenz4027 can you please add in the content what was covered by the tests; thank you!

**Comment by chenz4027** [comment]
@birsanv Sure let me update it

**Comment by chenz4027** [comment]
@birsanv Updated

**Comment by birsanv** [comment]
thank you Maggie

**Pull request merged**
