### PR TITLE
Fix placement yaml

### PR DESCRIPTION
**Pull request by chenz4027**
Signed-off-by: Maggie Chen <magchen@redhat.com>
https://github.com/open-cluster-management/backlog/issues/16136
https://github.com/open-cluster-management/backlog/issues/16171

### CODE REVIEW

**Comment by chenz4027** [comment]
/cc @KevinFCormier @fxiang1 
The only four tests that are failing are still caused by the invalid token while other tests all pass. I think it's safe to merge this PR as other tests all pass.
image

**Review by fxiang1 — APPROVED** [review]
Looks good!

**Pull request merged**
