### PR TITLE
Carbon cleanup + new header

### PR DESCRIPTION
**Pull request by KevinFCormier**

### CODE REVIEW

**Comment by richiepiya** [comment]
Fixed styling for the following pages...
- App table/advanced config pages:
    - page content placement
- Create app/editor pages:
    - YAML toggle
    - page content placement
- Single app page:
    - topology filter
    - cluster resource status nodes
    - page content placement

Screen Shot 2021-03-19 at 9 04 37 PM
Screen Shot 2021-03-19 at 9 04 51 PM
Screen Shot 2021-03-19 at 9 05 07 PM

**Review by fxiang1 — APPROVED** [review]
Looks good! Thanks!

**Pull request merged**
