### PR TITLE
Add applicationset create button to table

### PR DESCRIPTION
**Pull request by fxiang1**
https://github.com/open-cluster-management/backlog/issues/14364

- Added applicationset create button to table
- Remove old `Create application` button
- Updated cypress test to work with new button
- Update unit tests
- Updated ui-components version

image

image

disabledbuttontooltip

### CODE REVIEW

**Comment by chenz4027** [comment]
```
2021-08-05T16:02:04+00:00 Deployments done. Checking status.
2021-08-05T16:02:04+00:00 Cluster hub-1: ERROR Failed with status: ERROR WAIT_CSV_2
2021-08-05T16:02:04+00:00 Cluster hub-1: See cluster deploy log file (deploy-hub-1.log) for more details.
2021-08-05T16:02:04+00:00 ERROR One or more failed deployments.
{"component":"entrypoint","error":"wrapped process failed: exit status 1","file":"prow/entrypoint/run.go:80","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2021-08-05T16:02:04Z"}
error: failed to execute wrapped command: exit status 1
```


deploy hub-1:
```
2021-08-05T16:02:01+00:00 ERROR Deploy hub-1: Error CSV install failed after 15s
2021-08-05T16:02:01+00:00 ERROR Deploy hub-1: Error message: installing: waiting for deployment multiclusterhub-operator to become ready: Waiting for rollout to finish: 0 of 1 updated replicas are available...
2021-08-05T16:02:01+00:00 ERROR Deploy hub-1: Full CSV
{
```

Looks like the hub cluster failed to deploy : https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/open-cluster-management_application-ui/1323/pull-ci-open-cluster-management-application-ui-main-e2e-cluster/1423308054018920448/artifacts/e2e-cluster/ocm-e2e-clusterpool-cluster-deploy/artifacts/deploy-hub-1.log

FYI @ray-harris

**Comment by ray-harris** [comment]
I have not seen that error before. That sounds like it should be in status "Installing" rather than "Failed".

Here's where the deploy script is throwing the error:
https://steps.ci.openshift.org/reference/ocm-e2e-clusterpool-cluster-deploy#line645
```
        case "$_csv_status" in
            Failed)
                logf "$_log" "ERROR Deploy $_cluster: Error CSV install failed after ${_elapsed}s"
                local _msg
                _msg=$(jq -r .status.message csv.json 2> >(tee -a "$_log"))
                logf "$_log" "ERROR Deploy $_cluster: Error message: $_msg"
                logf "$_log" "ERROR Deploy $_cluster: Full CSV"
                jq . csv.json > >(tee -a "$_log") 2>&1
                echo "ERROR WAIT_CSV_2" > "$_status"
                return 1
                ;;
```

I'll see if I can track down why that's happening.

**Comment by ray-harris** [comment]
The retest you did is past the deployment, so it's likely something temporary. But it would still be nice to track it down.

**Comment by chenz4027** [comment]
Thanks @ray-harris for taking a look, I think we might have some bad builds in the past day, which caused the deploy failure as the installation was failing. Yeah it would be nice to identify the issue.

**Pull request merged**
