### PR TITLE
Remove translations 2.1

### PR DESCRIPTION
**Pull request by KevinFCormier**
https://github.com/open-cluster-management/backlog/issues/12642

### CODE REVIEW

**Comment by KevinFCormier** [comment]
@birsanv This defect is approved for 2.1.x now. If we want the e2e tests to pass, we will have to deploy a cluster with 2.1 and set up the old-style of Travis variables (from before cluster-keeper). Do you want me to do that or are you OK to just force merge it, as the risk should be low.

**Comment by birsanv** [comment]
@KevinFCormier I agree the risk is low and we should just force merge

**Review by chenz4027 — APPROVED** [review]
lgtm

**Review by birsanv — APPROVED** [review]
lgtm

**Pull request merged**
