### PR TITLE
Format properties file, add camelCase for kube entities

### PR DESCRIPTION
**Pull request by mancubus77**
issue https://github.com/open-cluster-management/application-ui/issues/1069
This is another PR for title formatting bases on "main" branch

### CODE REVIEW

**Comment by birsanv** [comment]
@Stanislav Kozlov can you please make sure you follow the steps covered here (https://github.com/open-cluster-management/application-ui/blob/main/CONTRIBUTING.md#contributing-a-patch) for code contribution. As discussed, we still need to have an issue opened first to describe the proposed change so we can review it before trying to deliver the changes. The next step is to make sure the unit tests pass. At the moment we don't have the e2e tests enabled to be run by external contributors, this is work in progress; we will run the e2e tests at the very end for you, once the issue is created and reviewed and your patch passes the prow tests ( junit )

**Comment by birsanv** [comment]
@mancubus77 I took your changes and fixed the failed junit tests, under this PR https://github.com/open-cluster-management/application-ui/pull/1074/files
We'll discuss options for checking in once we have a chance to review with the UX the proposed changes
We can use my PR or if you like you can apply my changes to your PR and fix the tests

**Comment by mancubus77** [comment]
thank you @birsanv 
I've applied your suggestions as you recommended.

**Pull request closed without merging**
