### PR TITLE
Issue15582

### PR DESCRIPTION
**Pull request by jeswanke**
https://github.com/open-cluster-management/backlog/issues/15582

### CODE REVIEW

**Review by chenz4027 — APPROVED** [review]
lgtm

**Comment by chenz4027** [comment]
/test e2e-cluster

If this still fail I think we could consider merging it manually. It passed before my approval and I think it's caused by https://github.com/open-cluster-management/backlog/issues/15899
FYI @jeswanke @fxiang1

**Comment by fxiang1** [comment]
Looks like this still failed. I will merge manually.

**Pull request merged**
