### PR TITLE
Fix problem with defining same channel twice in a single app

### PR DESCRIPTION
**Pull request by KevinFCormier**
open-cluster-management/backlog#12824

- For usingSameChannels, only check for channels before current
- Preserve reconcileRate when same URL selected again
- Hide reconcile rate when using same channel
- Condition was not correct - hiding was only happening for existing channels, not for using same channel

Signed-off-by: Kevin Cormier <kcormier@redhat.com>

### CODE REVIEW

**Comment by KevinFCormier** [comment]
@fxiang1 Can you please try this out and make sure it doesn't revert the fix for https://github.com/open-cluster-management/backlog/issues/12522?

**Comment by fxiang1** [comment]
@KevinFCormier Yep let me take a look

**Comment by fxiang1** [comment]
@KevinFCormier I just verified with your branch `kcormier-fix-duplicate-channel-secret-issue`, it doesn't revert the fix for open-cluster-management/backlog#12522

**Review by fxiang1 — APPROVED** [review]
Looks good. Thanks!

**Pull request merged**
