### PR TITLE
2.1 change branch name from master to main

### PR DESCRIPTION
**Pull request by chenz4027**
Signed-off-by: chenz4027 <magchen@redhat.com>

https://github.com/open-cluster-management/backlog/issues/13610

### CODE REVIEW

**Comment by chenz4027** [comment]
@birsanv @fxiang1 As discussed in: https://github.com/open-cluster-management/backlog/issues/13610#issuecomment-866892051. If we want the e2e tests to pass, we will have to deploy a cluster with 2.1 and set up the old-style of Travis variables (from before cluster-keeper). As those are only config variable change, are you okay to just force merge it, as the risk should be low?

Also do we need any approval to make change to 2.1?

**Review by fxiang1 — APPROVED** [review]
Looks good! Thanks Maggie!

**Comment by fxiang1** [comment]
I think we can merge this without e2e, since the change is very small. As for approval this is a test change so I think it should be ok.

**Review by birsanv — APPROVED** [review]
lgtm

**Pull request merged**
